"""empty message

Revision ID: 71aefdd84040
Revises: a5e853ffdc21
Create Date: 2021-02-07 03:53:55.600671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71aefdd84040'
down_revision = 'a5e853ffdc21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('author_follower_fkey', 'author', type_='foreignkey')
    op.drop_column('author', 'follower')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('follower', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('author_follower_fkey', 'author', 'user', ['follower'], ['id'])
    # ### end Alembic commands ###
